### ISSUE TITLE
How I can config other params, for example add Google Ads?

### ISSUE THREAD

**Issue by alexshelkov** [flpvsk/gatsby-plugin-gtag#10]
Where I can add configuration param to gtag. For example if I want to setup Google Ad I need to call config based on the docs: https://developers.google.com/analytics/devguides/collection/gtagjs/

```javascript
gtag('config', 'AW-123456789'); // AW-123456789 - my Google Ads ID
```

Also I want later to add GOOGLE_OPTIMIZE_TRACKING and GOOGLE_EXPERIMENT_ID, but have no idea where I can tweak this settings.

**Comment by flpvsk** [comment]
Hi Alex, there's no way to do that in that plugin. I've noticed that Gatsby team published a more elaborate plugin, maybe it would be a better fit for what you're trying to do? https://www.npmjs.com/package/gatsby-plugin-google-gtag

If not, I'd accept a PR. We might have to break backwards compatibility though to support some of it.

**Comment by alexshelkov** [comment]
Ok, will take a look, thx.
