### ISSUE TITLE
GTag plugin weakens Content Security Policy

### ISSUE THREAD

**Issue by r007** [flpvsk/gatsby-plugin-gtag#11]
Hi guys,

Please help. We have a gatsby app which is hosted on AWS. As you know, this code is being added to every page:

```html
<script>
    window.GATSBY_GTAG_PLUGIN_GA_TRACKING_ID = (
      'UA-96773019-1'
    );
    window.GATSBY_GTAG_PLUGIN_ANONYMIZE = false;

    var options = {
      send_page_view: false
    };
    if (false) {
      options.anonymize_ip = true;
    }

    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    window.gtag = gtag;
    gtag('js', new Date());
    gtag('config', 'UA-96773019-1', options);
</script>
```

Because of this piece of code, we have to add ```unsafe-inline``` to CSP policy. Which makes the whole policy useless. I suggest to rewrite the following from inline code to something more like this:

```html
<!-- Google GTag -->
<script src='gtag-config.js'></script>
```

The rewritten code has a number of advantages above and beyond working well with CSP; it's already best practice, regardless of the use of CSP. Inline JavaScript mixes structure and behavior in exactly the way you shouldn't. External resources are easier for browsers to cache, more understandable for developers, and conducive to compilation and minification.

Plus, there is no need to add ```unsafe-inline``` and website is protected against XSS attacks.

What do you think? Is this something you can do?

**Comment by flpvsk** [comment]
Hi @r007,

I'd be happy to accept a PR to make it into a flag. I would not make it the default behavior. It is not a recommended way to configure google analytics.

Let me clarify my point.

>  Inline JavaScript mixes structure and behavior in exactly the way you shouldn't.

Are you talking about the developer experience or the result HTML? If that's about dev experience, we can improve it internally. If it's about the result HTML, I don't think it's a problem.

> External resources are easier for browsers to cache

True, but they require an extra request on the first load. Every request counts on a slow network. There's a reason we don't put a hundred `<script src="external.js">` in the document.

At the same time if the page doesn't change, the whole page is cached together with this little inline bit.

> more understandable for developers

I'm happy to improve dev experience, but it has little to do with the final resulting HTML.

> conducive to compilation and minification

That's a valid point, but again, we can do compilation and minification *and still* do inlining. The two things are unrelated.

**Comment by r007** [comment]
The whole point of my message was that the browser has no mechanism by which to distinguish malicious payload from a legitimate inline script tag. CSP solves this problem by banning inline script entirely: it's the only way to be sure. Banning inline script is the biggest security win CSP provides, and banning inline style likewise hardens the application. It's a little bit of effort up front to ensure that things work correctly after moving all the code out-of-line, but that's a tradeoff that's well worth making.

If you absolutely must use inline GTag, CSP Level 2 offers backward compatibility for inline scripts by allowing you to whitelist specific inline scripts using either a cryptographic nonce (number used once) or a hash. An example with nonce would look something like this:

```jsx
const crypto = require('crypto');
let nonce = crypto.randomBytes(16).toString('base64');

const trackScript = (
    <script
      key="gatsby-plugin-gtag-inline-script"
      nonce="${nonce}"
      dangerouslySetInnerHTML={{ __html: scriptStr }}
      async
    />
  );
```
So the nonce attribute is way of telling browsers that the inline contents of a particular script or style element were not injected into the document by some (malicious) third party. Then need to simply add something like:
```html
<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-${nonce}';">
```

To ```setHeadComponents``` call. Both ways would work. It's just my guess, haven't tested it yet.

**Comment by flpvsk** [comment]
Yes, I get your point.

I think having `nonce` is a good default. Preferably implemented as a hash of the script string, because random makes builds unreproducible.

I'm not completely against putting the configuration into a separate file, but I would not make it the default. Happy to put it behind the flag.

**Comment by flpvsk** [comment]
Closing this for now.
