### ISSUE TITLE
How do you send events in your code with the gtag command?

### ISSUE THREAD

**Issue by tommymadeit** [flpvsk/gatsby-plugin-gtag#3]
Hi there,

I am trying to use this send events to my Google Analytics account. How should I do that?
If I try running gtag('event', 'action', { eventCategory: 'Test' } ) it will throw undefined since I didn't import it.

**Comment by flpvsk** [comment]
In the browser you can access it using the `window` object.

```js
if (window.gtag) {
  window.gtag('event', 'action', { event_category: 'test' });
}
```

**Comment by tommymadeit** [comment]
Thank you! It worked but I had to loading the gtag script without the plugin.
